import { gql } from "apollo-server"
import { userTypeDefs } from "./user/typdefs"
import { userResolvers } from "./user/resolvers"
import { postTypeDefs } from "./post/typdefs"
import { postResolvers } from "./post/resolvers"
import { apiFiltersTypeDefs } from "./api-filters/typedefs"
